name: deploy-container

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubunto-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: actions/checkout@master
      - name: shalzz/zola-deploy-action
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: docs
          BUILD_FLAGS: --drafts
          TOKEN: ${{ secrets.TOKEN }}
